language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update

script: |
  SYMFONY_DEPRECATIONS_HELPER=max[direct]=0 SYMFONY_PHPUNIT_VERSION=7.5 ./vendor/bin/simple-phpunit
